# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        AppBundle\Entity\User: bcrypt 

    role_hierarchy:
        ROLE_USER:       [ROLE_USER]

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        person:
            entity: { class: AppBundle:User, property: username }
            
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false


        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            form_login:
                check_path:               /api/login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false
        api:
            pattern:   ^/api
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        main:
            pattern: ^/
            form_login:
                login_path: login
                check_path: login
                always_use_default_target_path: true
                default_target_path: /
            logout:
                path: /logout
                target : /
            anonymous: true
            security: true
            
    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }

#        - { path: ^/rest/, roles: IS_AUTHENTICATED_FULLY}
        - { path: ^/login, allow_if: "is_anonymous() and !is_authenticated()" }
        - { path: ^/register, allow_if: "is_anonymous() and !is_authenticated()" }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY}